<a href="https://colab.research.google.com/github/Su-Han-Kim/AboutMe/blob/main/%EC%83%9D%ED%99%9C%EC%BD%94%EB%94%A9_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 0. 지도학습의 과정
1. 과거의 데이터 준비 
2. 모델의 구조를 만든다
3. 데이터로 모델을 학습(fitting model)
4. 모델을 이용하여 예측

# 1. Pandas

In [ ]:
import pandas as pd
 
###########################
# 파일로부터 데이터 읽어오기
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
레모네이드 = pd.read_csv(파일경로)
 
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
 
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
 


In [ ]:
# 데이터의 모양확인
print(레모네이드.shape)
print(보스턴.shape)
print(아이리스.shape)

# 각각의 데이터 확인해보기
print(레모네이드.head())
print(보스턴.head())
print(아이리스.head())


(6, 2)
(506, 14)
(150, 5)
   온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48
      crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2  
   꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa


In [ ]:
# 독립변수와 종속변수 분리
독립 = 레모네이드[['온도']]
종속 = 레모네이드[['판매량']]
print(독립.shape, 종속.shape)
 
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)
 
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종']]
print(독립.shape, 종속.shape)


(6, 1) (6, 1)
(506, 13) (506, 1)
(150, 4) (150, 1)


# 2. 첫번째 딥러닝 - 레모네이드 판매 예측

## 1. Loss


- 모델의 학습이 얼마나 진행되었는가
- 모델의 예측값과 정답이 얼마나 차이나는가
- Loss = mean((예측 - 결과)^2)

In [ ]:
import tensorflow as tf
import pandas as pd

# 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
레모네이드 = pd.read_csv(파일경로)
레모네이드.head()

# 종속변수, 독립변수
독립 = 레모네이드[['온도']]
종속 = 레모네이드[['판매량']]
print(독립.shape, 종속.shape)

(6, 1) (6, 1)


In [ ]:
# 모델을 만듭니다.
X = tf.keras.layers.Input(shape=[1]) #독립변수의 column의 개수
Y = tf.keras.layers.Dense(1)(X) #종속변수의 column의 개수
model = tf.keras.models.Model(X, Y) 
model.compile(loss='mse')

In [ ]:
# 모델을 학습시킵니다. 
#epoch: 모델을 몇 번 학습 시킬 것인가 
#verbose=0: 화면출력X
model.fit(독립, 종속, epochs=1000, verbose=0) 

In [ ]:
# 모델을 이용합니다. 
print(model.predict(독립))


[[40.059322]
 [42.032223]
 [44.005127]
 [45.978027]
 [47.950928]
 [49.923832]]


In [ ]:
print(model.predict([[15]]))

[[30.19481]]


In [ ]:
print(model.get_weights())

[array([[1.9729017]], dtype=float32), array([0.60128665], dtype=float32)]


# 3. 두번째 딥러닝 - 보스턴 집값 예측

## 1. 수식과 퍼셉트론

- model를 fit하는 과정
  1. Input layer: 독립변수 N개의 입력을 받는 입력층을 구성
  2. Dense layer: 종속변수 M개의 출력을 만드는 출력층을 구성
  3. 독립변수 N개의 입력으로부터 M개의 출력을 만들어내는 구조를 만드는 것
  4. **수식**: y1 = w1x1 + w2x2 + ... b / y2 = w1x1 + w2x2 + ... b ...  
    -> **퍼셉트론**: 다수의 입력으로부터 하나의 결과를 내보내는 알고리즘
  5. 컴퓨터는 학습과정에서 입력된 데이터를 보고 w(가중치)와 b(편향)를 찾는 것


In [ ]:
import tensorflow as tf
import pandas as pd

파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)

독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']] #해당 도시의 집값의 median
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [ ]:
# 모델을 만듭니다.
X = tf.keras.layers.Input(shape=[13]) #독립변수의 column의 개수
Y = tf.keras.layers.Dense(1)(X) #종속변수의 column의 개수
model = tf.keras.models.Model(X, Y) 
model.compile(loss='mse')

In [ ]:
# 모델을 학습시킵니다. 
#epoch: 모델을 몇 번 학습 시킬 것인가 
#verbose=0: 화면출력X
model.fit(독립, 종속, epochs=10) 

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 27.1956
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 26.4537
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 26.5892
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 26.6399
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 27.0057
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 26.5121
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 26.8543
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 26.7119
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 26.4802
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 26.9513


In [ ]:
# 4. 모델을 이용합니다
print(model.predict(독립[5:10]))
# 종속변수 확인
print(종속[5:10])

[[26.61534 ]
 [21.45558 ]
 [18.363708]
 [ 9.69677 ]
 [18.011045]]
   medv
5  28.7
6  22.9
7  27.1
8  16.5
9  18.9


In [ ]:
# 모델의 수식 확인
print(model.get_weights())

[array([[-0.08981714],
       [ 0.07509096],
       [-0.05291929],
       [ 3.3951948 ],
       [ 1.5365646 ],
       [ 3.8505714 ],
       [ 0.01958147],
       [-0.8489031 ],
       [ 0.14704806],
       [-0.00910299],
       [ 0.03042164],
       [ 0.01673809],
       [-0.5909596 ]], dtype=float32), array([2.760172], dtype=float32)]


# 4. 세번째 딥러닝 - 아이리스 품종 분류

## 1. One-hot encoding

- 범주형 변수의 경우 숫자만 들어가야 할 퍼셉트론에 적합하지 않음
- one-hot encoding: 범주형 변수를 1, 0의 숫자형 데이터로 바꿔주는 것

## 2. Softmax & Cross-entropy

- Classification이란 분류를 확률로 추측하는 것: ex) 비가 올 확률, 품종이 setosa일 확률... 
- 확률의 특징은 0 이상 1 이하
- softmax를 사용하는 이유: 분류를 확률(0과 1 사이의 결과)로 예측하기 위해 필요함 
- 수식은 -inf ~ inf까지 예측이 가능하지만 Classification에서는 0과 1사이의 예측만 필요함
- 활성화 함수: 최종 결과를 만들기 전, 퍼셉트론의 출력이 어떤 형태로 나가야 하는지 조절하는 함수 ex) softmax(y1 = w1x1 + w2x2 + ... b) 
- Cross-entropy: Classification에 사용하는 Loss 함수

In [ ]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [ ]:
# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)
print(아이리스)
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']] # one-hot enncoding으로 인해 종속변수가 3개로 늘어남
print(독립.shape, 종속.shape)

     꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0     5.1  3.5    1.4   0.2          1              0             0
1     4.9  3.0    1.4   0.2          1              0             0
2     4.7  3.2    1.3   0.2          1              0             0
3     4.6  3.1    1.5   0.2          1              0             0
4     5.0  3.6    1.4   0.2          1              0             0
..    ...  ...    ...   ...        ...            ...           ...
145   6.7  3.0    5.2   2.3          0              0             1
146   6.3  2.5    5.0   1.9          0              0             1
147   6.5  3.0    5.2   2.0          0              0             1
148   6.2  3.4    5.4   2.3          0              0             1
149   5.9  3.0    5.1   1.8          0              0             1

[150 rows x 7 columns]
(150, 4) (150, 3)


In [ ]:
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [ ]:
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0964 - accuracy: 0.9733
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0958 - accuracy: 0.9733
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0964 - accuracy: 0.9733
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0958 - accuracy: 0.9733
Epoch 5/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0959 - accuracy: 0.9733
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0958 - accuracy: 0.9733
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0968 - accuracy: 0.9733
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0958 - accuracy: 0.9733
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0960 - accuracy: 0.9733
Epoch 10/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0960 - accuracy: 0.9733


In [ ]:
# 4. 모델을 이용합니다
# 맨 처음 데이터 5개
print(model.predict(독립[:5]))
print(종속[:5])
 
# 맨 마지막 데이터 5개
print(model.predict(독립[-5:]))
print(종속[-5:])
 
###########################
# weights & bias 출력
print(model.get_weights())

[[9.9998105e-01 1.8955692e-05 2.2302511e-12]
 [9.9986005e-01 1.3998458e-04 7.3136726e-11]
 [9.9994493e-01 5.5046792e-05 1.8530715e-11]
 [9.9974078e-01 2.5923239e-04 2.1505651e-10]
 [9.9998450e-01 1.5510152e-05 1.6660912e-12]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
[[1.5948406e-10 4.9943786e-02 9.5005625e-01]
 [6.9516065e-10 9.4695315e-02 9.0530461e-01]
 [1.6270392e-09 1.4532538e-01 8.5467470e-01]
 [7.9977983e-11 3.7526079e-02 9.6247393e-01]
 [4.3998472e-09 1.9433257e-01 8.0566746e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1
[array([[ 1.7193602 ,  0.2958006

# 5. 네번째 딥러닝 - 신경망의 완성:히든레이어

- 히든 레이어: Input과 output layer사이에 추가한 퍼셉트론

In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [2]:
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
 
# 종속변수, 독립변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [10]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')



Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 13)]              0         
                                                                 
 dense_4 (Dense)             (None, 10)                140       
                                                                 
 dense_5 (Dense)             (None, 1)                 11        
                                                                 
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [16]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=100)

Epoch 1/100
16/16 [==============================] - 0s 2ms/step - loss: 27.2571
Epoch 2/100
16/16 [==============================] - 0s 2ms/step - loss: 28.2023
Epoch 3/100
16/16 [==============================] - 0s 2ms/step - loss: 26.5122
Epoch 4/100
16/16 [==============================] - 0s 2ms/step - loss: 27.5410
Epoch 5/100
16/16 [==============================] - 0s 2ms/step - loss: 25.8185
Epoch 6/100
16/16 [==============================] - 0s 2ms/step - loss: 28.1673
Epoch 7/100
16/16 [==============================] - 0s 2ms/step - loss: 27.9616
Epoch 8/100
16/16 [==============================] - 0s 2ms/step - loss: 27.7252
Epoch 9/100
16/16 [==============================] - 0s 2ms/step - loss: 26.0639
Epoch 10/100
16/16 [==============================] - 0s 2ms/step - loss: 28.4616
Epoch 11/100
16/16 [==============================] - 0s 2ms/step - loss: 27.5323
Epoch 12/100
16/16 [==============================] - 0s 2ms/step - loss: 25.7907
Epoch 13/100
16/16 [=====

In [15]:
# 모델 구조 확인
model.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 13)]              0         
                                                                 
 dense_4 (Dense)             (None, 10)                140       
                                                                 
 dense_5 (Dense)             (None, 1)                 11        
                                                                 
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [17]:
# 4. 모델을 이용합니다
print(model.predict(독립[:5]))
print(종속[:5])

[[28.870955]
 [25.374535]
 [28.893562]
 [29.364683]
 [28.693426]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [18]:
# 이산형

# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

In [19]:
# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)

In [20]:
# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [21]:
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [22]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 1s 4ms/step - loss: 1.4723 - accuracy: 0.2867
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 1.2790 - accuracy: 0.4133
Epoch 3/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1878 - accuracy: 0.4800
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1196 - accuracy: 0.5267
Epoch 5/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0655 - accuracy: 0.5867
Epoch 6/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0220 - accuracy: 0.6200
Epoch 7/100
5/5 [==============================] - 0s 3ms/step - loss: 0.9812 - accuracy: 0.6933
Epoch 8/100
5/5 [==============================] - 0s 3ms/step - loss: 0.9460 - accuracy: 0.6600
Epoch 9/100
5/5 [==============================] - 0s 3ms/step - loss: 0.9078 - accuracy: 0.6600
Epoch 10/100
5/5 [==============================] - 0s 3ms/step - loss: 0.8719 - accuracy: 0.6600
Epoch 11/100
5/5 [===========

In [23]:
model.summary()

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense_6 (Dense)             (None, 8)                 40        
                                                                 
 dense_7 (Dense)             (None, 8)                 72        
                                                                 
 dense_8 (Dense)             (None, 8)                 72        
                                                                 
 dense_9 (Dense)             (None, 3)                 27        
                                                                 
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [24]:
# 4. 모델을 이용합니다
print(model.predict(독립[:5]))
print(종속[:5])

[[9.9855596e-01 1.4439690e-03 1.5180724e-07]
 [9.9791008e-01 2.0895479e-03 3.0332566e-07]
 [9.9750888e-01 2.4905968e-03 5.2806189e-07]
 [9.9570787e-01 4.2911777e-03 9.6345354e-07]
 [9.9825698e-01 1.7427859e-03 2.1510003e-07]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
